# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mmqgis_float_to_text_form.ui'
#
# Created: Fri Dec 20 08:54:19 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_mmqgis_float_to_text_form(object):
    def setupUi(self, mmqgis_float_to_text_form):
        mmqgis_float_to_text_form.setObjectName(_fromUtf8("mmqgis_float_to_text_form"))
        mmqgis_float_to_text_form.setWindowModality(QtCore.Qt.ApplicationModal)
        mmqgis_float_to_text_form.setEnabled(True)
        mmqgis_float_to_text_form.resize(372, 403)
        mmqgis_float_to_text_form.setMouseTracking(False)
        self.buttonBox = QtGui.QDialogButtonBox(mmqgis_float_to_text_form)
        self.buttonBox.setGeometry(QtCore.QRect(110, 370, 160, 26))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.label = QtGui.QLabel(mmqgis_float_to_text_form)
        self.label.setGeometry(QtCore.QRect(10, 320, 261, 22))
        self.label.setObjectName(_fromUtf8("label"))
        self.filename = QtGui.QLineEdit(mmqgis_float_to_text_form)
        self.filename.setGeometry(QtCore.QRect(10, 340, 261, 21))
        self.filename.setReadOnly(False)
        self.filename.setObjectName(_fromUtf8("filename"))
        self.browse = QtGui.QPushButton(mmqgis_float_to_text_form)
        self.browse.setGeometry(QtCore.QRect(280, 340, 79, 26))
        self.browse.setObjectName(_fromUtf8("browse"))
        self.sourcelayer = QtGui.QComboBox(mmqgis_float_to_text_form)
        self.sourcelayer.setGeometry(QtCore.QRect(10, 30, 351, 27))
        self.sourcelayer.setObjectName(_fromUtf8("sourcelayer"))
        self.label_4 = QtGui.QLabel(mmqgis_float_to_text_form)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 121, 22))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.fieldnames = QtGui.QListWidget(mmqgis_float_to_text_form)
        self.fieldnames.setGeometry(QtCore.QRect(10, 90, 341, 121))
        self.fieldnames.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.fieldnames.setObjectName(_fromUtf8("fieldnames"))
        self.label_5 = QtGui.QLabel(mmqgis_float_to_text_form)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 121, 22))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.separator = QtGui.QComboBox(mmqgis_float_to_text_form)
        self.separator.setGeometry(QtCore.QRect(10, 240, 131, 22))
        self.separator.setObjectName(_fromUtf8("separator"))
        self.separator.addItem(_fromUtf8(""))
        self.separator.addItem(_fromUtf8(""))
        self.separator.addItem(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(mmqgis_float_to_text_form)
        self.label_6.setGeometry(QtCore.QRect(10, 220, 121, 22))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.decimals = QtGui.QComboBox(mmqgis_float_to_text_form)
        self.decimals.setGeometry(QtCore.QRect(210, 240, 131, 22))
        self.decimals.setObjectName(_fromUtf8("decimals"))
        self.decimals.addItem(_fromUtf8(""))
        self.decimals.addItem(_fromUtf8(""))
        self.decimals.addItem(_fromUtf8(""))
        self.decimals.addItem(_fromUtf8(""))
        self.decimals.addItem(_fromUtf8(""))
        self.decimals.addItem(_fromUtf8(""))
        self.decimals.addItem(_fromUtf8(""))
        self.decimals.addItem(_fromUtf8(""))
        self.decimals.addItem(_fromUtf8(""))
        self.decimals.addItem(_fromUtf8(""))
        self.decimals.addItem(_fromUtf8(""))
        self.decimals.addItem(_fromUtf8(""))
        self.decimals.addItem(_fromUtf8(""))
        self.label_7 = QtGui.QLabel(mmqgis_float_to_text_form)
        self.label_7.setGeometry(QtCore.QRect(210, 220, 121, 22))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.prefix = QtGui.QLineEdit(mmqgis_float_to_text_form)
        self.prefix.setGeometry(QtCore.QRect(10, 290, 131, 21))
        self.prefix.setObjectName(_fromUtf8("prefix"))
        self.label_8 = QtGui.QLabel(mmqgis_float_to_text_form)
        self.label_8.setGeometry(QtCore.QRect(10, 270, 121, 22))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(mmqgis_float_to_text_form)
        self.label_9.setGeometry(QtCore.QRect(210, 270, 121, 22))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.suffix = QtGui.QLineEdit(mmqgis_float_to_text_form)
        self.suffix.setGeometry(QtCore.QRect(210, 290, 131, 21))
        self.suffix.setObjectName(_fromUtf8("suffix"))

        self.retranslateUi(mmqgis_float_to_text_form)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), mmqgis_float_to_text_form.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), mmqgis_float_to_text_form.reject)
        QtCore.QMetaObject.connectSlotsByName(mmqgis_float_to_text_form)

    def retranslateUi(self, mmqgis_float_to_text_form):
        mmqgis_float_to_text_form.setWindowTitle(QtGui.QApplication.translate("mmqgis_float_to_text_form", "Float to Text", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mmqgis_float_to_text_form", "Output Shapefile", None, QtGui.QApplication.UnicodeUTF8))
        self.filename.setText(QtGui.QApplication.translate("mmqgis_float_to_text_form", "temp.shp", None, QtGui.QApplication.UnicodeUTF8))
        self.browse.setText(QtGui.QApplication.translate("mmqgis_float_to_text_form", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("mmqgis_float_to_text_form", "Source Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("mmqgis_float_to_text_form", "Fields to Convert", None, QtGui.QApplication.UnicodeUTF8))
        self.separator.setItemText(0, QtGui.QApplication.translate("mmqgis_float_to_text_form", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.separator.setItemText(1, QtGui.QApplication.translate("mmqgis_float_to_text_form", "Comma", None, QtGui.QApplication.UnicodeUTF8))
        self.separator.setItemText(2, QtGui.QApplication.translate("mmqgis_float_to_text_form", "Space", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("mmqgis_float_to_text_form", "000\'s Separator", None, QtGui.QApplication.UnicodeUTF8))
        self.decimals.setItemText(0, QtGui.QApplication.translate("mmqgis_float_to_text_form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.decimals.setItemText(1, QtGui.QApplication.translate("mmqgis_float_to_text_form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.decimals.setItemText(2, QtGui.QApplication.translate("mmqgis_float_to_text_form", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.decimals.setItemText(3, QtGui.QApplication.translate("mmqgis_float_to_text_form", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.decimals.setItemText(4, QtGui.QApplication.translate("mmqgis_float_to_text_form", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.decimals.setItemText(5, QtGui.QApplication.translate("mmqgis_float_to_text_form", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.decimals.setItemText(6, QtGui.QApplication.translate("mmqgis_float_to_text_form", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.decimals.setItemText(7, QtGui.QApplication.translate("mmqgis_float_to_text_form", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.decimals.setItemText(8, QtGui.QApplication.translate("mmqgis_float_to_text_form", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.decimals.setItemText(9, QtGui.QApplication.translate("mmqgis_float_to_text_form", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.decimals.setItemText(10, QtGui.QApplication.translate("mmqgis_float_to_text_form", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.decimals.setItemText(11, QtGui.QApplication.translate("mmqgis_float_to_text_form", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.decimals.setItemText(12, QtGui.QApplication.translate("mmqgis_float_to_text_form", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("mmqgis_float_to_text_form", "Decimal Places", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("mmqgis_float_to_text_form", "Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("mmqgis_float_to_text_form", "Suffix", None, QtGui.QApplication.UnicodeUTF8))

