# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_teamqgis.ui'
#
# Created: Thu Dec 19 11:05:34 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_teamqgis(object):
    def setupUi(self, teamqgis):
        teamqgis.setObjectName(_fromUtf8("teamqgis"))
        teamqgis.resize(308, 328)
        teamqgis.setWindowTitle(_fromUtf8("teamqgis"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.browseFrame = QtGui.QFrame(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseFrame.sizePolicy().hasHeightForWidth())
        self.browseFrame.setSizePolicy(sizePolicy)
        self.browseFrame.setAutoFillBackground(False)
        self.browseFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.browseFrame.setObjectName(_fromUtf8("browseFrame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.browseFrame)
        self.gridLayout_2.setMargin(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.widget = QtGui.QWidget(self.browseFrame)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.listCombo = QtGui.QComboBox(self.widget)
        self.listCombo.setToolTip(_fromUtf8(""))
        self.listCombo.setAccessibleName(_fromUtf8(""))
        self.listCombo.setAccessibleDescription(_fromUtf8(""))
        self.listCombo.setEditable(True)
        self.listCombo.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.listCombo.setObjectName(_fromUtf8("listCombo"))
        self.gridLayout.addWidget(self.listCombo, 1, 2, 1, 1)
        self.previousButton = QtGui.QToolButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previousButton.sizePolicy().hasHeightForWidth())
        self.previousButton.setSizePolicy(sizePolicy)
        self.previousButton.setMaximumSize(QtCore.QSize(21, 16777215))
        self.previousButton.setToolTip(_fromUtf8(""))
        self.previousButton.setAccessibleName(_fromUtf8(""))
        self.previousButton.setAccessibleDescription(_fromUtf8(""))
        self.previousButton.setText(_fromUtf8("<"))
        self.previousButton.setObjectName(_fromUtf8("previousButton"))
        self.gridLayout.addWidget(self.previousButton, 1, 1, 1, 1)
        self.nextButton = QtGui.QToolButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextButton.sizePolicy().hasHeightForWidth())
        self.nextButton.setSizePolicy(sizePolicy)
        self.nextButton.setMaximumSize(QtCore.QSize(21, 16777215))
        self.nextButton.setToolTip(_fromUtf8(""))
        self.nextButton.setAccessibleName(_fromUtf8(""))
        self.nextButton.setAccessibleDescription(_fromUtf8(""))
        self.nextButton.setText(_fromUtf8(">"))
        self.nextButton.setObjectName(_fromUtf8("nextButton"))
        self.gridLayout.addWidget(self.nextButton, 1, 3, 1, 1)
        self.currentPosLabel = QtGui.QLabel(self.widget)
        self.currentPosLabel.setToolTip(_fromUtf8(""))
        self.currentPosLabel.setAccessibleName(_fromUtf8(""))
        self.currentPosLabel.setAccessibleDescription(_fromUtf8(""))
        self.currentPosLabel.setText(_fromUtf8("0/0"))
        self.currentPosLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.currentPosLabel.setObjectName(_fromUtf8("currentPosLabel"))
        self.gridLayout.addWidget(self.currentPosLabel, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 1, 1, 1, 1)
        self.widget_2 = QtGui.QWidget(self.browseFrame)
        self.widget_2.setMinimumSize(QtCore.QSize(276, 40))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.widget_2)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.panCheck = QtGui.QCheckBox(self.widget_2)
        self.panCheck.setChecked(True)
        self.panCheck.setObjectName(_fromUtf8("panCheck"))
        self.gridLayout_4.addWidget(self.panCheck, 1, 0, 1, 1)
        self.scaleCheck = QtGui.QCheckBox(self.widget_2)
        self.scaleCheck.setCheckable(True)
        self.scaleCheck.setChecked(True)
        self.scaleCheck.setObjectName(_fromUtf8("scaleCheck"))
        self.gridLayout_4.addWidget(self.scaleCheck, 1, 2, 1, 1)
        self.editFormButton = QtGui.QToolButton(self.widget_2)
        self.editFormButton.setToolTip(_fromUtf8(""))
        self.editFormButton.setAccessibleDescription(_fromUtf8(""))
        self.editFormButton.setText(_fromUtf8("..."))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../icons/openform.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editFormButton.setIcon(icon)
        self.editFormButton.setObjectName(_fromUtf8("editFormButton"))
        self.gridLayout_4.addWidget(self.editFormButton, 1, 4, 1, 1)
        self.actionButton = QtGui.QToolButton(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionButton.sizePolicy().hasHeightForWidth())
        self.actionButton.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../icons/action.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionButton.setIcon(icon1)
        self.actionButton.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.actionButton.setObjectName(_fromUtf8("actionButton"))
        self.gridLayout_4.addWidget(self.actionButton, 1, 3, 1, 1)
        self.gridLayout_2.addWidget(self.widget_2, 3, 1, 1, 1)
        self.frame = QtGui.QFrame(self.browseFrame)
        self.frame.setMinimumSize(QtCore.QSize(276, 84))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.translateLeftButton = QtGui.QPushButton(self.frame)
        self.translateLeftButton.setEnabled(False)
        self.translateLeftButton.setGeometry(QtCore.QRect(16, 29, 75, 23))
        self.translateLeftButton.setObjectName(_fromUtf8("translateLeftButton"))
        self.translateRightButton = QtGui.QPushButton(self.frame)
        self.translateRightButton.setEnabled(False)
        self.translateRightButton.setGeometry(QtCore.QRect(180, 30, 75, 23))
        self.translateRightButton.setObjectName(_fromUtf8("translateRightButton"))
        self.translateDownButton = QtGui.QPushButton(self.frame)
        self.translateDownButton.setEnabled(False)
        self.translateDownButton.setGeometry(QtCore.QRect(99, 58, 75, 23))
        self.translateDownButton.setObjectName(_fromUtf8("translateDownButton"))
        self.translateUpButton = QtGui.QPushButton(self.frame)
        self.translateUpButton.setEnabled(False)
        self.translateUpButton.setGeometry(QtCore.QRect(99, 0, 75, 23))
        self.translateUpButton.setObjectName(_fromUtf8("translateUpButton"))
        self.applyChangesButton = QtGui.QPushButton(self.frame)
        self.applyChangesButton.setEnabled(False)
        self.applyChangesButton.setGeometry(QtCore.QRect(115, 30, 41, 23))
        self.applyChangesButton.setObjectName(_fromUtf8("applyChangesButton"))
        self.gridLayout_2.addWidget(self.frame, 2, 1, 1, 1)
        self.frame_2 = QtGui.QFrame(self.browseFrame)
        self.frame_2.setMinimumSize(QtCore.QSize(276, 94))
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.fieldOneNameComboBox = QtGui.QComboBox(self.frame_2)
        self.fieldOneNameComboBox.setGeometry(QtCore.QRect(0, 10, 131, 20))
        self.fieldOneNameComboBox.setObjectName(_fromUtf8("fieldOneNameComboBox"))
        self.fieldOneValueComboBox = QtGui.QComboBox(self.frame_2)
        self.fieldOneValueComboBox.setEnabled(False)
        self.fieldOneValueComboBox.setGeometry(QtCore.QRect(138, 10, 131, 22))
        self.fieldOneValueComboBox.setObjectName(_fromUtf8("fieldOneValueComboBox"))
        self.fieldTwoNameComboBox = QtGui.QComboBox(self.frame_2)
        self.fieldTwoNameComboBox.setGeometry(QtCore.QRect(0, 40, 131, 20))
        self.fieldTwoNameComboBox.setObjectName(_fromUtf8("fieldTwoNameComboBox"))
        self.fieldTwoValueComboBox = QtGui.QComboBox(self.frame_2)
        self.fieldTwoValueComboBox.setEnabled(False)
        self.fieldTwoValueComboBox.setGeometry(QtCore.QRect(138, 40, 131, 22))
        self.fieldTwoValueComboBox.setObjectName(_fromUtf8("fieldTwoValueComboBox"))
        self.fieldThreeNameComboBox = QtGui.QComboBox(self.frame_2)
        self.fieldThreeNameComboBox.setGeometry(QtCore.QRect(0, 70, 131, 20))
        self.fieldThreeNameComboBox.setObjectName(_fromUtf8("fieldThreeNameComboBox"))
        self.fieldThreeValueComboBox = QtGui.QComboBox(self.frame_2)
        self.fieldThreeValueComboBox.setEnabled(False)
        self.fieldThreeValueComboBox.setGeometry(QtCore.QRect(138, 70, 131, 22))
        self.fieldThreeValueComboBox.setObjectName(_fromUtf8("fieldThreeValueComboBox"))
        self.gridLayout_2.addWidget(self.frame_2, 5, 1, 1, 1)
        self.gridLayout_3.addWidget(self.browseFrame, 0, 0, 1, 1)
        teamqgis.setWidget(self.dockWidgetContents)

        self.retranslateUi(teamqgis)
        QtCore.QMetaObject.connectSlotsByName(teamqgis)

    def retranslateUi(self, teamqgis):
        self.panCheck.setText(_translate("teamqgis", "pan", None))
        self.scaleCheck.setText(_translate("teamqgis", "scale", None))
        self.actionButton.setText(_translate("teamqgis", "...", None))
        self.translateLeftButton.setText(_translate("teamqgis", "Move Left", None))
        self.translateRightButton.setText(_translate("teamqgis", "Move Right", None))
        self.translateDownButton.setText(_translate("teamqgis", "Move Down", None))
        self.translateUpButton.setText(_translate("teamqgis", "Move Up", None))
        self.applyChangesButton.setText(_translate("teamqgis", "Apply", None))

